---

stages:
  - lint

variables:
  APP_NAME: bas-base-images

# == Jobs ==

lint-definitions:
  stage: lint
  image:
    name: hashicorp/packer
    entrypoint: [""]
  variables:
    DIGITALOCEAN_API_TOKEN: xxx
  script:
    - "packer validate packer/templates/antarctica-centos7.json"
