---

stages:
  - lint

variables:
  APP_NAME: bas-base-images

# == Jobs ==

lint-definitions:
  stage: lint
  image:
    name: hashicorp/packer
    entrypoint: [""]
  script:
    - "packer validate templates/antarctica-centos7.json"
