---

version: "2"

services:
  packer:
    image: hashicorp/packer:1.2.5
    working_dir: /usr/src/app
    entrypoint: ash
    volumes:
      - .:/usr/src/app
    environment:
      - DIGITALOCEAN_API_TOKEN=$DIGITALOCEAN_TOKEN
